#!/bin/bash

year=' 2026'
db=~/Documents/Admin/shortcuts/PROJECTS$year

mkdir -p "$db/NEW PROJECT"
mkdir -p "$db/NEW PROJECT/[01] PROJECT FILES/AE JOBS" "NEW PROJECT/[01] PROJECT FILES/AE JOBS/_OLD SAVES" "NEW PROJECT/[01] PROJECT FILES/PREMIERE JOBS" "NEW PROJECT/[01] PROJECT FILES/ILLUSTRATOR"
mkdir -p "$db/NEW PROJECT/[02] MEDIA/IMAGES" "NEW PROJECT/[02] MEDIA/RAW" "NEW PROJECT/[02] MEDIA/VIDEO"
mkdir -p "$db/NEW PROJECT/[03] GRAPHICS/ASSETS" "NEW PROJECT/[03] GRAPHICS/FONTS" "NEW PROJECT/[03] GRAPHICS/INSPIRATION" "NEW PROJECT/[03] GRAPHICS/RENDERS"
mkdir -p "$db/NEW PROJECT/[04] AUDIO/MUSIC" "NEW PROJECT/[04] AUDIO/SOUND EFFECTS" "NEW PROJECT/[04] AUDIO/VOICE/PROCESSED" "NEW PROJECT/[04] AUDIO/VOICE/RAW" "NEW PROJECT/[04] AUDIO/VOICE/SCRATCH"
mkdir -p "$db/NEW PROJECT/[05] EXPORTS/OFFLINE" "NEW PROJECT/[05] EXPORTS/ONLINE/TV" "NEW PROJECT/[05] EXPORTS/ONLINE/WEB" "NEW PROJECT/[05] EXPORTS/STYLEFRAMES" "NEW PROJECT/[05] EXPORTS/TESTS"
mkdir -p "$db/NEW PROJECT/[XX] ADMIN"

open -R "$db/NEW PROJECT"
